{
    "config": {
        "abort": {
            "already_configured": "Enheten \u00e4r redan konfigurerad"
        },
        "error": {
            "cannot_connect": "Det gick inte att ansluta.",
            "invalid_auth": "Ogiltig autentisering",
            "unknown": "Ov\u00e4ntat fel"
        },
        "step": {
            "user": {
                "data": {
                    "host": "V\u00e4rd",
                    "name": "Namn",
                    "password": "L\u00f6senord",
                    "port": "Port",
                    "ssl": "Anv\u00e4nder ett SSL certifikat",
                    "username": "Anv\u00e4ndarnamn",
                    "verify_ssl": "Verifiera SSL-certifikat"
                }
            }
        }
    },
    "entity": {
        "button": {
            "abort_downloads": {
                "name": "Avbryta alla p\u00e5g\u00e5ende nedladdningar"
            },
            "delete_finished": {
                "name": "Ta bort f\u00e4rdiga filer/paket"
            },
            "restart": {
                "name": "Starta om pyload-k\u00e4rnan"
            },
            "restart_failed": {
                "name": "Starta om alla misslyckade filer"
            }
        },
        "sensor": {
            "active": {
                "name": "Aktiva nedladdningar"
            },
            "free_space": {
                "name": "Ledigt utrymme"
            },
            "queue": {
                "name": "Nedladdningar i k\u00f6"
            },
            "speed": {
                "name": "Hastighet"
            },
            "total": {
                "name": "F\u00e4rdiga nedladdningar"
            }
        },
        "switch": {
            "reconnect": {
                "name": "Automatisk \u00e5teranslutning"
            }
        }
    },
    "exceptions": {
        "setup_authentication_exception": {
            "message": "Autentiseringen misslyckades f\u00f6r {username}, kontrollera dina inloggningsuppgifter"
        },
        "setup_parse_exception": {
            "message": "Det gick inte att tolka data fr\u00e5n pyLoad API, f\u00f6rs\u00f6k igen senare"
        },
        "setup_request_exception": {
            "message": "Det gick inte att ansluta och h\u00e4mta data fr\u00e5n pyLoad API, f\u00f6rs\u00f6k igen senare"
        }
    }
}